In [3]:
import pandas as pd

In [58]:
url_dict = {}
url_dict["primary"] = 'https://data.nsw.gov.au/data/dataset/818ae0d8-d7fb-4b62-963c-7263fdb8e1ca/resource/7a662477-3585-42ba-8e19-1387d6790588/download/2020-2024-enrolments-primary-schools-1.csv'
url_dict["secondary"] = 'https://data.nsw.gov.au/data/dataset/818ae0d8-d7fb-4b62-963c-7263fdb8e1ca/resource/afee026b-6d18-4cd5-991c-74292db81322/download/2020-2024-enrolments-secondary-schools-1.csv'
url_dict["centra"] = 'https://data.nsw.gov.au/data/dataset/818ae0d8-d7fb-4b62-963c-7263fdb8e1ca/resource/12fb9921-1a09-4661-966f-7ec5a5d4f9ab/download/2020-2024-enrolments-central-schools-1.csv'
url_dict["ssp"] = 'https://data.nsw.gov.au/data/dataset/818ae0d8-d7fb-4b62-963c-7263fdb8e1ca/resource/5f0736cd-9b26-48e2-a45d-b74c7cbe83ed/download/2020-2024-enrolments-ssp-1.csv'

In [14]:
# oh darn csv is malformed
df_all_school_types = pd.DataFrame({})

for school_type in url_dict.keys():

    df_per_school_type =pd.read_csv(
        # url_dict[school_type],
        'https://data.nsw.gov.au/data/dataset/818ae0d8-d7fb-4b62-963c-7263fdb8e1ca/resource/7a662477-3585-42ba-8e19-1387d6790588/download/2020-2024-enrolments-primary-schools-1.csv'
    )

    df_per_school_type['school_type'] = school_type
    df_per_school_type['_load_timestamp'] = pd.Timestamp('now')
    df_per_school_type['_source'] = url_dict[school_type]


    df_all_school_types = pd.concat([df_all_school_types, df_per_school_type])



# some rows are none
# df_ram_all_years[df_ram_all_years["School Code"].isna()]

# fixing up picking total rows from CSVs
df_all_school_types = df_all_school_types.dropna(subset=["School Code"])

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 29765: invalid start byte

# There is an API for this data source lets give it a go

In [42]:
import dlt
from dlt.sources.helpers import requests

# Specify the URL of the API endpoint
url = 'https://data.nsw.gov.au/data/api/3/action/datastore_search?resource_id=7a662477-3585-42ba-8e19-1387d6790588&limit=100000000'
# Make a request and check if it was successful
response = requests.get(url)
response.raise_for_status()

In [44]:
result = response.json()["result"]['records']

In [47]:
df = pd.json_normalize(result)

In [50]:
df.tail(50)

,School Performance Directorate,School Code,School Name,2020,2021,2022,2023,2024
1612,Rural South and West,3554,Yenda Public School,97,108,112,113,114
1613,Metropolitan South,3986,Yennora Public School,241,233,246,247,247
1614,Metropolitan South,5120,Yeo Park Infants School,52,52,52,54,56
1615,Rural South and West,3556,Yerong Creek Public School,25,23,17,13,13
1616,Rural North,3559,Yetman Public School,15,14,17,13,9
1617,Rural South and West,3561,Yoogali Public School,42,42,42,45,53
1618,Metropolitan South & West,4482,York Public School,552,525,507,488,492
1619,Rural South and West,4131,Young North Public School,303,293,314,314,307
1620,Rural South and West,3563,Young Public School,495,493,524,491,532
1621,Metropolitan South & West,4124,Yowie Bay Public School,440,415,412,409,350
1622,Regional North & West,3566,Zig Zag Public School,94,101,108,96,109
1623,Metropolitan North,4686,Tallawong Public School [27],0,0,0,0,31
1624,Metropolitan South and West,4687,Gulyangarri Public School [28],0,0,0,0,129
1625,Rural South and West,4690,Jindabyne Public School [29],0,0,0,0,283
1626,Metropolitan North,4691,Nirimba Fields Public School [30],0,0,0,0,117
1627,None,None,None,None,None,None,None,461914.0
1628,None,None,None,None,None,None,None,None
1629,None,None,None,None,None,None,None,None
1630,[1] New school in 2020,None,None,None,None,None,None,None
1631,[2] New school in 2019,None,None,None,None,None,None,None
1632,[3] New school in 2019,None,None,None,None,None,None,None
1633,[4] In recess since 2020,None,None,None,None,None,None,None
1634,[5] New school in 2022,None,None,None,None,None,None,None
1635,[6] In recess since 2021,None,None,None,None,None,None,None
1636,[7] New school in 2021,None,None,None,None,None,None,None
1637,[8] In recess since 2021,None,None,None,None,None,None,None
1638,[9] New school in 2021,None,None,None,None,None,None,None
1639,[10] New school in 2020,None,None,None,None,None,None,None
1640,[12] In recess since 2021,None,None,None,None,None,None,None
1641,[13] In recess in 2022,None,None,None,None,None,None,None
1642,[14] New school in 2021,None,None,None,None,None,None,None
1643,[15] In recess in 2022,None,None,None,None,None,None,None
1644,[16] In recess since 2020,None,None,None,None,None,None,None
1645,[17] New school in 2019,None,None,None,None,None,None,None
1646,[18] New school in 2021,None,None,None,None,None,None,None
1647,[19] In recess since 2021,None,None,None,None,None,None,None
1648,[20] Re-opened in 2019,None,None,None,None,None,None,None
1649,[21] New school in 2022,None,None,None,None,None,None,None
1650,[22] In recess in 2022,None,None,None,None,None,None,None
1651,[23] In recess in 2022,None,None,None,None,None,None,None
1652,[24] New school in 2020,None,None,None,None,None,None,None
1653,[25] In recess in 2022,None,None,None,None,None,None,None
1654,[26] In recess since 2019,None,None,None,None,None,None,None
1655,[27] New School in 2024,None,None,None,None,None,None,None
1656,[28] New School in 2024,None,None,None,None,None,None,None
1657,[29] New School in 2024,None,None,None,None,None,None,None
1658,[30] New School in 2024,None,None,None,None,None,None,None
1659,[31] In recess in 2023,None,None,None,None,None,None,None
1660,[32] In recess in 2024,None,None,None,None,None,None,None
1661,[33] In recess in 2024,None,None,None,None,None,None,None

### fixes required
assume if no school code then row isnt a school

In [60]:
url_dict = {}
url_dict["primary"] = 'https://data.nsw.gov.au/data/api/3/action/datastore_search?resource_id=7a662477-3585-42ba-8e19-1387d6790588&limit=99999999'
url_dict["secondary"] = 'https://data.nsw.gov.au/data/api/3/action/datastore_search?resource_id=afee026b-6d18-4cd5-991c-74292db81322&limit=99999999'
url_dict["centra"] = 'https://data.nsw.gov.au/data/api/3/action/datastore_search?resource_id=12fb9921-1a09-4661-966f-7ec5a5d4f9ab&limit=99999999'
url_dict["ssp"] = 'https://data.nsw.gov.au/data/api/3/action/datastore_search?resource_id=5f0736cd-9b26-48e2-a45d-b74c7cbe83ed&limit=99999999'

In [66]:
# oh darn csv is malformed
df_all_school_types = pd.DataFrame({})

for school_type in url_dict.keys():

    response = requests.get(url_dict[school_type])
    response.raise_for_status()
    result = response.json()["result"]['records']
    df_per_school_type = pd.json_normalize(result)

    

    df_per_school_type['school_type'] = school_type
    df_per_school_type['_load_timestamp'] = pd.Timestamp('now')
    df_per_school_type['_source'] = url_dict[school_type]


    df_all_school_types = pd.concat([df_all_school_types, df_per_school_type])



# some rows are none
# df_ram_all_years[df_ram_all_years["School Code"].isna()]

# fixing up picking total rows from CSVs
df_all_school_types = df_all_school_types.dropna(subset=["School Code"])

In [68]:
df_all_school_types.tail()

,School Performance Directorate,School Code,School Name,2020,2021,2022,2023,2024,school_type,_load_timestamp,_source,Operational Directorate
112,NaN,5609,Woniora Road School,39,41,39,41,41,ssp,2024-06-18 11:53:24.357765,https://data.nsw.gov.au/data/api/3/action/data...,Metropolitan South
113,NaN,5764,Woodberry Learning Centre,19,19,9,17,17,ssp,2024-06-18 11:53:24.357765,https://data.nsw.gov.au/data/api/3/action/data...,Regional North & West
114,NaN,5766,Yandelora School [3],99,102,105,100,101,ssp,2024-06-18 11:53:24.357765,https://data.nsw.gov.au/data/api/3/action/data...,Regional South
115,NaN,5769,Yawarra Community School [4],16,22,33,40,53,ssp,2024-06-18 11:53:24.357765,https://data.nsw.gov.au/data/api/3/action/data...,Regional North & West
116,NaN,5460,Yudi Gunyi School,25,26,30,32,43,ssp,2024-06-18 11:53:24.357765,https://data.nsw.gov.au/data/api/3/action/data...,Metropolitan South

In [69]:
df_all_school_types.shape

(2217, 12)